---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1525344/nilaisantri/app
    - /bin/cp -r app/Models $DEPLOYPATH/Models
    - /bin/cp -r app/Views $DEPLOYPATH/Views
    - /bin/cp -r app/Controllers $DEPLOYPATH/Controllers
