---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1525344/nilaisantri/app/

    - hook: post_deploy
      commands:
        # Sync Models
        - /bin/cp -rv app/Models/* ${DEPLOYPATH}Models/

        # Sync Views
        - /bin/cp -rv app/Views/* ${DEPLOYPATH}Views/

        # Sync Controllers
        - /bin/cp -rv app/Controllers/* ${DEPLOYPATH}Controllers/

        - /bin/chown -R u1525344:u1525344 ${DEPLOYPATH}
        - /bin/find ${DEPLOYPATH} -type d -exec chmod 755 {} \;
        - /bin/find ${DEPLOYPATH} -type f -exec chmod 644 {} \;
